# Generated by Django 2.2.27 on 2022-02-10 10:24

import django.db.models.deletion
from django.db import migrations, models

from .. import settings


class Migration(migrations.Migration):

    dependencies = [
        ('last_active', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastactive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_active', to=settings.AUTH_USER_MODEL),
        ),
    ]
